### ISSUE TITLE
kCreateClean - ensure data is removed

### ISSUE THREAD

**Issue by blasscoc** [TGSAI/mdio-cpp#88]
If we open a dataset with kCreateClean, ensure any exiting data is removed.

**Comment by BrianMichell** [comment]
I have tested the kCreateClean behavior by creating an MDIO with Variables X, Y, GRID and populating GRID and X and writing to disk. I then created a new MDIO with the same path but with Variables INLINE, XLINE, GRID and read GRID.

GRID *data* gets deleted while X and Y remain fully intact. 

The resolution to this issue is either:
1. Check for an existing MDIO, use the delete utility, populate the new MDIO. This will add latency and reduce the async ability of creating a Dataset.
2. Move the `kCreateClean` definition to a new namespace, `mdio::development::kCreateClean` for instance, to further differentiate it from production code.
3. Do nothing and continue documenting it.
